import { motion } from 'framer-motion';
import { BookOpen, ExternalLink, Type, Edit, Search, Layers } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import InfoCard from '../components/InfoCard';
import favcImage from '../imgs/favc.jpg'; // or .png

const AiLiteraturePage = () => {
  const literatureExamples = [
    {
      title: 'The Electric Sonnets',
      excerpt: '"In digital skies, where silicon dreams unfold,\nWhere human thoughts and machine minds entwine;\nNew verses form, as ancient tales are told\nThrough neural nets, a strange design..."',
      type: 'Poetry',
      details: 'Generated by a GPT model fine-tuned on classic and modern poetry collections',
      delay: 0.1
    },
    {
      title: 'Algorithms of Memory',
      excerpt: 'The city was a maze of data, streets pulsing with information that Clara couldn\'t decode. She adjusted her neural interface, feeling the familiar tingle as it synchronized with her thoughts. "Show me the path," she whispered, and the world transformed before her eyes...',
      type: 'Short Fiction',
      details: 'Created using a hybrid AI system trained on science fiction and technological narratives',
      delay: 0.2
    },
    {
      title: 'The Pattern Recognition Problem',
      excerpt: 'The emergence of complex linguistic forms in large language models presents a fascinating paradox: systems without consciousness producing work that mimics the depth of human introspection. This study examines the boundaries between computational pattern matching and true understanding...',
      type: 'Academic Essay',
      details: 'Collaborative work between AI language models and human researchers',
      delay: 0.3
    },
    {
      title: 'Dialogues with the Machine',
      excerpt: 'Human: What does it mean to be creative?\nAI: Creativity exists in the spaces between known patterns, in the unexpected connections that surprise even the creator. I can simulate this through statistical inference, but you experience it as a mysterious emergence from consciousness...',
      type: 'Philosophical Dialogue',
      details: 'Conversations exploring creativity and consciousness between humans and advanced language models',
      delay: 0.4
    }
  ];

  return (
    <div>
      <div className="bg-gradient-to-r from-blue-600 to-teal-600 py-16">
        <PageHeader
          title="AI in Literature"
          subtitle="Exploring how artificial intelligence is transforming writing, storytelling, and literary expression."
          alignment="center"
        />
      </div>

      <section className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="lg:flex lg:items-center lg:justify-between">
            <motion.div 
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5 }}
              className="lg:w-1/2 lg:pr-12"
            >
              <h2 className="text-3xl font-bold text-gray-900">The Written Word, Reimagined</h2>
              <p className="mt-4 text-lg text-gray-600">
                Artificial intelligence is opening new frontiers in literature and storytelling. From poetry 
                and fiction to non-fiction and journalism, AI is transforming how writers create and how 
                readers experience the written word.
              </p>
              <p className="mt-4 text-lg text-gray-600">
                Language models can now generate coherent, creative text across various styles and genres, 
                suggesting plot developments, creating characters, editing drafts, and even producing entire 
                works. This isn't replacing human creativity but augmenting it, offering writers new tools 
                and inspiration while challenging our understanding of authorship and creativity.
              </p>
            </motion.div>
            
            <motion.div 
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.2, duration: 0.5 }}
              className="mt-10 lg:mt-0 lg:w-1/2"
            >
              <img 
                src={favcImage}  
                alt="AI writing assistant" 
                className="rounded-lg shadow-lg w-full h-auto"
              />
            </motion.div>
          </div>
        </div>
      </section>

      <section className="py-16 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-gray-900">AI-Generated Literary Works</h2>
            <p className="mt-4 text-xl text-gray-600 max-w-3xl mx-auto">
              Explore examples of literature created through collaboration between human writers and artificial intelligence.
            </p>
          </motion.div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {literatureExamples.map((example) => (
              <motion.div 
                key={example.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: example.delay, duration: 0.5 }}
                className="bg-white rounded-lg shadow-md p-6"
              >
                <div className="inline-block bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm font-medium mb-3">
                  {example.type}
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-3">{example.title}</h3>
                <div className="bg-gray-50 p-4 rounded-md mb-4 font-serif italic">
                  <p className="whitespace-pre-line text-gray-700">{example.excerpt}</p>
                </div>
                <p className="text-gray-600 text-sm">{example.details}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-gray-900">AI Writing Applications</h2>
            <p className="mt-4 text-xl text-gray-600 max-w-3xl mx-auto">
              Discover how AI is being used across different aspects of writing and publishing.
            </p>
          </motion.div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <InfoCard 
              icon={Type}
              title="Creative Writing Assistance"
              content="AI systems that help generate ideas, overcome writer's block, suggest plot developments, and create characters for fiction writers."
              delay={0.1}
            />
            <InfoCard 
              icon={Edit}
              title="Editing and Revision"
              content="Tools that analyze text for clarity, style, grammar, and tone, offering suggestions for improvement beyond traditional spelling and grammar checks."
              delay={0.2}
            />
            <InfoCard 
              icon={Search}
              title="Research Assistance"
              content="AI systems that can summarize extensive research materials, identify relevant information, and even generate background content on specific topics."
              delay={0.3}
            />
            <InfoCard 
              icon={Layers}
              title="Translation and Adaptation"
              content="Advanced tools that preserve nuance, cultural context, and literary style when translating or adapting written works across languages."
              delay={0.4}
            />
          </div>
        </div>
      </section>

      <section className="py-16 bg-gradient-to-r from-teal-50 to-blue-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="lg:flex lg:items-center lg:justify-between">
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="lg:w-1/2 lg:pr-8"
            >
              <h2 className="text-3xl font-bold text-gray-900">The Future of Storytelling</h2>
              <p className="mt-4 text-lg text-gray-600">
                As AI continues to evolve, we're entering an era where stories might adapt to each reader, 
                where collaborative writing between humans and machines becomes seamless, and where new 
                literary forms emerge that wouldn't be possible without AI.
              </p>
              <p className="mt-4 text-lg text-gray-600">
                These developments raise fascinating questions about creativity, authorship, and the essence 
                of storytelling. Rather than replacing human writers, AI is becoming a new kind of collaborative 
                partner that expands what's possible in literature.
              </p>
              
              <div className="mt-8">
                <h3 className="text-xl font-bold text-gray-900 mb-4">Try AI Writing Tools</h3>
                <div className="flex flex-wrap gap-3">
                  <a 
                    href="https://openai.com/chatgpt" 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 transition shadow-sm"
                  >
                    ChatGPT <ExternalLink size={14} className="ml-1" />
                  </a>
                  <a 
                    href="https://novelai.net/" 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-blue-700 bg-blue-100 hover:bg-blue-200 transition shadow-sm"
                  >
                    NovelAI <ExternalLink size={14} className="ml-1" />
                  </a>
                  <a 
                    href="https://sudowrite.com/" 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-teal-700 bg-teal-100 hover:bg-teal-200 transition shadow-sm"
                  >
                    Sudowrite <ExternalLink size={14} className="ml-1" />
                  </a>
                </div>
              </div>
            </motion.div>
            
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.5 }}
              className="mt-10 lg:mt-0 lg:w-1/2"
            >
              <div className="bg-white p-6 rounded-lg shadow-md">
                <h3 className="text-xl font-bold text-gray-900 mb-4">Interactive AI Story Demo</h3>
                <p className="text-gray-600 mb-6">
                  Type a prompt to continue the story. The AI will generate the next part based on your input.
                </p>
                
                <div className="bg-gray-50 p-4 rounded-md mb-4">
                  <p className="text-gray-700">
                    The old lighthouse stood at the edge of the cliff, its beam cutting through the fog. Sarah approached cautiously, the key heavy in her pocket. She had no idea what she would find inside, but the mysterious letter had been clear: "Come alone. All will be revealed."
                  </p>
                </div>
                
                <div className="mt-4">
                  <input
                    type="text"
                    placeholder="What happens next? (e.g., 'Sarah unlocked the door...')"
                    className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                  <button
                    className="mt-2 w-full px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition"
                  >
                    Continue Story
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default AiLiteraturePage;